name: service_name
services:
  web:
    build: .
    container_name: web_name
    ports:
      - "8XXX:80"
    volumes:
      - ./:/var/www/html
    networks:
      - database-network

networks:
  database-network:
    external: true
